SuggestreamProject/urls.py
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from games import views as game_views


urlpatterns = [
    path('', game_views.login_redirect, name='login_redirect'),
    path('home/', include('games.urls', namespace='home')),
    path('games-alphabetical/', game_views.GamesPageAlphabetically.as_view(), name='all-alphabetical'),
    path('games-rating/', game_views.GamesPageByRating.as_view(), name='all-metacritic'),
    path('recommended/', game_views.Recommended.as_view(), name='recommended'),
    path('genre-search/', game_views.GenreSearch.as_view(), name='genre-search'),
    path('genre-results/', game_views.GamesPageByGenre.as_view(), name='genre-results'),
    path('title-search/', game_views.TitleSearch.as_view(), name='title-search'),
    path('register/', game_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='games/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='games/logout.html'), name='logout'),
    path('profile/', game_views.profile, name='profile'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

games/urls.py
from django.urls import path
from . import views
from django.urls import path, include
from games import views as game_views

app_name = 'games'

urlpatterns = [
    path('', views.home, name='index'),
    path('accounts/', include('django.contrib.auth.urls'), name='register'),
    path('<pk>/detail', views.DetailPage.as_view(), name='detail'),
    path('favourites/', game_views.SelectFavouriteGenres.as_view(), name='favourites'),
    path('favourites/submitted/', game_views.SubmitFavourites.as_view(), name='submitted'),
]

games/forms.py
from SuggestreamProject import settings
from .models import Profile
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


GENRE_CHOICES = [
    ('twod', '2D'), ('action', 'Action'), ('adventure', 'Adventure'), ('arcade', 'Arcade'), ('building', 'Building'),
    ('cartoon', 'Cartoon'), ('city_builder', 'City Builder'), ('class_based', 'Class-based'), ('coop', 'Co-op'),
    ('comedy', 'Comedy'), ('competitive', 'Competitive'), ('crafting', 'Crafting'), ('destruction', 'Destruction'),
    ('difficult', 'Difficult'), ('driving', 'Driving'), ('dystopian', 'Dystopian'), ('fantasy', 'Fantasy'),
    ('first_person', 'First Person'), ('fps', 'FPS'), ('free_to_play', 'Free To Play'), ('futuristic', 'Futuristic'),
    ('historical', 'Historical'), ('horror', 'Horror'), ('indie', 'Indie'), ('magic', 'Magic'), ('medieval', 'Medieval'),
    ('military', 'Military'), ('moba', 'MOBA'), ('multiplayer', 'Multiplayer'), ('open_world', 'Open World'),
    ('post_apocalyptic', 'Post-apocalyptic'), ('procedural_generation', 'Procedural Generation'), ('puzzle', 'Puzzle'),
    ('racing', 'Racing'), ('rpg', 'RPG'), ('rts', 'RTS'), ('sandbox', 'Sandbox'), ('scifi', 'Sci-fi'), ('shooter', 'Shooter'),
    ('side_scroller', 'Side Scroller'), ('singleplayer', 'Singleplayer'), ('soccer', 'Soccer'), ('space', 'Space'),
    ('sports', 'Sports'), ('stealth', 'Stealth'), ('strategy', 'Strategy'), ('survival', 'Survival'),
    ('third_person', 'Third Person'), ('tower_defence', 'Tower Defence'), ('vr', 'VR'), ('war', 'War'), ('zombie', 'Zombie')
]


#Create a class which inherits from Django's UserCreationForm class and add fields necessary for my users
class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=True, max_length=50)
    last_name = forms.CharField(required=True, max_length=50)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']

    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit)
        return user


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('user',
                  'twod', 'action', 'adventure', 'arcade', 'building', 'cartoon', 'city_builder', 'class_based', 'coop', 'comedy',
                  'competitive', 'crafting', 'destruction', 'difficult', 'driving', 'dystopian', 'fantasy', 'fighting', 'first_person',
                  'fps', 'free_to_play', 'futuristic', 'historical', 'horror', 'indie', 'magic', 'medieval', 'military', 'moba',
                  'multiplayer', 'open_world', 'post_apocalyptic', 'procedural_generation', 'puzzle', 'racing', 'rpg', 'rts',
                  'sandbox', 'scifi', 'shooter', 'side_scroller', 'singleplayer', 'soccer', 'space', 'sports', 'stealth', 'strategy',
                  'survival', 'third_person', 'tower_defence', 'vr', 'war', 'zombie')

games/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views import generic
from django.views.generic import View
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Game, Genre, Profile
from .forms import UserRegisterForm, ProfileForm
from django.forms.models import model_to_dict
from operator import itemgetter
from itertools import chain
import random

# Displays all results as a listview on the index page
def home(request):
    return render(request, 'games/index.html')


class GenreSearch(generic.ListView):
    template_name = 'games/genresearch.html'
    context_object_name = 'genre_list'

    def get_queryset(self):
        return Genre.objects.order_by("name")


class TitleSearch(generic.ListView):
    template_name = 'games/titlesearch.html'
    context_object_name = 'game_list'

    def get_queryset(self):
        return Game.objects.order_by("name")


class GamesPageAlphabetically(generic.ListView):
    template_name = 'games/allgames.html'
    context_object_name = 'game_list'

    def get_queryset(self):
        return Game.objects.order_by("name")


class GamesPageByRating(generic.ListView):
    template_name = 'games/allgames.html'
    context_object_name = 'game_list'

    def get_queryset(self):
        return Game.objects.order_by("-metacritic")


class SelectFavouriteGenres(generic.ListView):
    template_name = 'games/favourites.html'
    context_object_name = 'genre_list'

    def get_queryset(self):
        return Genre.objects.order_by("name")


class SubmitFavourites(generic.ListView):
    template_name = 'games/thankyou.html'
    context_object_name = 'game_list'

    def get_queryset(self):
        #Grabs the genre name and user's ID from the GenreSearch URL query, these are used to query all games with
        #the selected genre, and to then grab the profile of the currently logged in user to increment their preferences
        genre1_name = self.request.GET.get("genre1")
        genre2_name = self.request.GET.get("genre2")
        genre3_name = self.request.GET.get("genre3")
        user_id = self.request.GET.get("userid")

        #If the user isn't logged in then their preferences can't be updated
        if user_id != "None":
            user = Profile.objects.get(user_id=user_id)
            print("-----------------------------------")
            print("User = ", user)
            print("Genre1 = ", genre1_name)
            print("Genre2 = ", genre2_name)
            print("Genre3 = ", genre3_name)
            print("User ID = ", user_id)
            print()

            #Replaces spaces with underscores as genres like "Class based" are "class_based" in preferences
            if " " in genre1_name:
                edited = genre1_name.replace(" ", "_")
                genre1ToUpdate = edited.lower()
            else:
                edited = genre1_name
                genre1ToUpdate = edited.lower()

            print("Genre1 to update lowercase: ", genre1ToUpdate)

            #Discrepencies to the correction above are all handled here to ensure the game genre and
            #user profile genre preferences match
            if genre1ToUpdate == "2d":                  genre1ToUpdate = "twod"
            elif genre1ToUpdate == "class-based":       genre1ToUpdate = "class_based"
            elif genre1ToUpdate == "co-op":             genre1ToUpdate = "coop"
            elif genre1ToUpdate == "post-apocalyptic":  genre1ToUpdate = "post_apocalyptic"
            elif genre1ToUpdate == "sci-fi":            genre1ToUpdate = "scifi"


            #Second genre
            if " " in genre2_name:
                edited = genre2_name.replace(" ", "_")
                genre2ToUpdate = edited.lower()
            else:
                edited = genre2_name
                genre2ToUpdate = edited.lower()

            print("Genre2 to update lowercase: ", genre2ToUpdate)

            # Discrepencies to the correction above are all handled here to ensure the game genre and
            # user profile genre preferences match
            if genre2ToUpdate == "2d":                  genre2ToUpdate = "twod"
            elif genre2ToUpdate == "class-based":       genre2ToUpdate = "class_based"
            elif genre2ToUpdate == "co-op":             genre2ToUpdate = "coop"
            elif genre2ToUpdate == "post-apocalyptic":  genre2ToUpdate = "post_apocalyptic"
            elif genre2ToUpdate == "sci-fi":            genre2ToUpdate = "scifi"

            # Third genre
            if " " in genre3_name:
                edited = genre3_name.replace(" ", "_")
                genre3ToUpdate = edited.lower()
            else:
                edited = genre3_name
                genre3ToUpdate = edited.lower()

            print("Genre3 to update lowercase: ", genre3ToUpdate)

            # Discrepencies to the correction above are all handled here to ensure the game genre and
            # user profile genre preferences match
            if genre3ToUpdate == "2d":                  genre3ToUpdate = "twod"
            elif genre3ToUpdate == "class-based":       genre3ToUpdate = "class_based"
            elif genre3ToUpdate == "co-op":             genre3ToUpdate = "coop"
            elif genre3ToUpdate == "post-apocalyptic":  genre3ToUpdate = "post_apocalyptic"
            elif genre3ToUpdate == "sci-fi":            genre3ToUpdate = "scifi"

            print("Genre1 to update after validation: ", genre1ToUpdate)
            print("Genre2 to update after validation: ", genre2ToUpdate)
            print("Genre3 to update after validation: ", genre3ToUpdate)

            #Dynamically retrieves the user's preference value of the queried genre
            retrieve1 = getattr(user, genre1ToUpdate)
            print("Profile value: ", genre1ToUpdate, " = ", retrieve1)

            retrieve2 = getattr(user, genre2ToUpdate)
            print("Profile value: ", genre2ToUpdate, " = ", retrieve2)

            retrieve3 = getattr(user, genre3ToUpdate)
            print("Profile value: ", genre3ToUpdate, " = ", retrieve3)

            #Sets this queried genre to +1 of what it already was to learn they've shown interest in this genre
            setattr(user, genre1ToUpdate, retrieve1 + 1)
            setattr(user, genre2ToUpdate, retrieve2 + 1)
            setattr(user, genre3ToUpdate, retrieve3 + 1)

            #Save this change in the database
            user.save()
            print("User's ", genre1ToUpdate, " after incrementing = ", getattr(user, genre1ToUpdate))
            print("User's ", genre2ToUpdate, " after incrementing = ", getattr(user, genre2ToUpdate))
            print("User's ", genre3ToUpdate, " after incrementing = ", getattr(user, genre3ToUpdate))

    #TODO FOR MULTI GENRE SEARCH - return Game.objects.filter(genres__name=str('Action')).filter(genres__name=str('Side Scroller'))


class GamesPageByGenre(generic.ListView):
    template_name = 'games/genresearchresults.html'
    context_object_name = 'game_list'

    def get_queryset(self):
        #Grabs the genre name and user's ID from the GenreSearch URL query, these are used to query all games with
        #the selected genre, and to then grab the profile of the currently logged in user to increment their preferences
        genre_name = self.request.GET.get("genre")
        user_id = self.request.GET.get("userid")

        #If the user is logged in then their preferences can be updated
        if user_id != "None":
            user = Profile.objects.get(user_id=user_id)
            print("-----------------------------------")
            print("User = ", user)
            print("Genre = ", genre_name)
            print("User ID = ", user_id)
            print()

            #Replaces spaces with underscores as genres like "Class based" are "class_based" in preferences
            if " " in genre_name:
                edited = genre_name.replace(" ", "_")
                genreToUpdate = edited.lower()
            else:
                edited = genre_name
                genreToUpdate = edited.lower()

            print("Genre to update lowercase: ", genreToUpdate)

            #Discrepencies to the correction above are all handled here to ensure the game genre and
            #user profile genre preferences match
            if genreToUpdate == "2d":                   genreToUpdate = "twod"
            elif genreToUpdate == "class-based":        genreToUpdate = "class_based"
            elif genreToUpdate == "co-op":              genreToUpdate = "coop"
            elif genreToUpdate == "post-apocalyptic":   genreToUpdate = "post_apocalyptic"
            elif genreToUpdate == "sci-fi":             genreToUpdate = "scifi"

            print("Genre to update after validation: ", genreToUpdate)

            #Dynamically retrieves the user's preference value of the queried genre
            retrieve = getattr(user, genreToUpdate)
            print("Profile value: ", genreToUpdate, " = ", retrieve)

            #Sets this queried genre to +1 of what it already was to learn they've shown interest in this genre
            setattr(user, genreToUpdate, retrieve + 1)

            #Save this change in the database
            user.save()
            print("User's ", genreToUpdate, " after incrementing = ", getattr(user, genreToUpdate))


        #Once either the preferences have been updated or if there is no user ID, retrieve all games that match the genre they selected
        print("GENRE NAME = ", genre_name)
        return Game.objects.filter(genres__name=str(genre_name))

    def get_context_data(self, **kwargs):
        context = super(GamesPageByGenre, self).get_context_data(**kwargs)

        genre_name = self.request.GET.get("genre")

games/templates/games/allgames.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>All Games</title>
    {% extends 'games/base.html' %}

</head>
<body>

{% block body %}
<div class="content-section">
    <div>

    <!--If the list of games exists, create a table and populate each row with a game-->
    {% if game_list %}
        {% if game_list.0.name == "Adventure Capitalist" %} <h1>Games in Alphabetical Order</h1>
        {% elif game_list.0.metacritic > 95 %} <h1>Games by Metacritic Rating</h1>
    {% endif %}

    <div class="table-responsive">
    <table class="table table-bordered">
        <!--Sets up headings-->
        <thead class="thead-dark">
        <tr>
          <th scope="col" class="align-middle d-none d-xl-table-cell" style="width: 40%">Image</th>
          <th scope="col" class="align-middle" style="width: 20%">Title</th>
          <th scope="col" class="align-middle d-none d-md-table-cell" style="width: 10%">Developer</th>
          <th scope="col" class="align-middle" style="width: 10%">Metacritic</th>
          <th scope="col" class="align-middle" style="width: 20%">More Details</th>
        </tr>
        </thead>

        {% for game in game_list %}
        <tbody>
        <tr>
            <td class="align-middle d-none d-xl-table-cell"><img src="{{ game.image }}"></td>
            <td class="align-middle">{{ game.name }}</td>
            <td class="align-middle d-none d-md-table-cell">{{ game.developer }}</td>

            {% if game.metacritic == 0 %}
                <td class="align-middle">N/A</td>
            {% else %}
                <td class="align-middle">{{ game.metacritic }}</td>
            {% endif %}

            <!--The detail page requires a game ID as part of its URL, this grabs the game that is selected's ID-->
            <td class="align-middle"><a href="{% url 'games:detail' game.id %}"><img src="https://img.icons8.com/ios/50/000000/circled-right-2-filled.png"/></a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <small><a href="https://icons8.com/icon/26196/forward-button-filled">Forward Button Filled icon by Icons8</a></small>
    </div>

    {% else %}
        <p>No games found! Please report this to Stuart.</p>
    {% endif %}

    </div>
</div>
{% endblock %}

</body>
</html>

games/templates/games/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'games/style.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
    <script src="{% static 'games/script.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>

<body>

<header class="site-header">
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand mr-4" href="{% url 'games:index' %}">Suggestream</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <div class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'recommended' %}?userid={{ user.id }}">Recommended For You</a>
            {% endif %}
            <a class="nav-item nav-link" href="{% url 'genre-search' %}">Search By Genre</a>
        </div>
        <!-- Navbar Right Side -->
        <div class="navbar-nav">
            <!--If the user is logged in show the logout button and vice versa-->
            {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'profile' %}">My Profile</a>
              <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            {% else %}
              <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
              <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
            {% endif %}
        </div>
      </div>
    </div>
  </nav>
</header>

<main role="main" class="container">
  <div class="row">
    <div class="col-md-12">
      {% block content %}{% endblock %}
    </div>
  </div>
</main>


<div class="container">
{%  block body %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}
</div>

</body>
</html>

games/templates/games/favourites.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Favourites</title>
    {% extends 'games/base.html' %}
</head>
<body>

{% block body %}
<div class="content-section">
<div>
<h1>Favourite Genres</h1>
<br>
{% if genre_list %}

<h3>Please select your 3 favourite genres</h3>

<!--3 dropdown boxes are created and filled with all of the game's genres, when a genre is selected
    the value is stored in p tag below as a variable.-->
<select id="genres1" required="required" onchange="selectedValueGenre1()">
    <option selected="selected">Please select a genre</option>
    {% for genre1 in genre_list %}
        <option value="{{ genre1 }}">{{ genre1 }}</option>
    {% endfor %}
</select>

<br>

<select id="genres2" required="required" onchange="selectedValueGenre2()">
    <option selected="selected">Please select a second genre</option>
    {% for genre2 in genre_list %}
        <option value="{{ genre2 }}">{{ genre2 }}</option>
    {% endfor %}
</select>

<br>

<select id="genres3" required="required" onchange="selectedValueGenre3()">
    <option selected="selected">Please select a third genre</option>
    {% for genre3 in genre_list %}
        <option value="{{ genre3 }}">{{ genre3 }}</option>
    {% endfor %}
</select>

<!--By default these p tags are hidden because they act as variables for the javascript functions,
    each of the 'selected' p tags will change once a genre is chosen from each dropdown box, if any
    of them are still A, B or C upon submission, submission will fail.-->
<p id="selected1" hidden="hidden">A</p>
<p id="selected2" hidden="hidden">B</p>
<p id="selected3" hidden="hidden">C</p><br>

<!--Clicking this button will send a query to update the 3 selected genre values on the user's profile,
    otherwise the page will refresh as it will not be successful (as they will not have selected all 3.)-->
<form action="javascript:document.location.href=setAction({{ user.id }})">
    <button type="submit" class="btn btn-primary btn-lg">Submit Favourites</button>
</form>

{% else %}
    <p>Error! Please report this to Stuart.</p>
{% endif %}

</div>
</div>
{%  endblock %}

</body>
</html>

games/templates/games/genresearchresults.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Genre Search Results</title>
    {% extends 'games/base.html' %}

</head>
<body>

{%  block body %}
<div class="content-section">
<div>

{% if searched_genre %}
    <h1>{{ searched_genre.first }} Games</h1>
{% else %}
    <h1>Genre Search Results</h1>
{% endif %}

<!--If the list of games exists, create a table and populate each row with a game-->
{% if game_list %}
<div class="table-responsive">

    <table class="table table-bordered">
        <!--Sets up headings-->
        <thead class="thead-dark">
        <tr>
          <th scope="col" style="width: 40%" class="d-none d-xl-table-cell">Image</th>
          <th scope="col" style="width: 20%">Title</th>
          <th scope="col" style="width: 10%" class="d-none d-md-table-cell">Developer</th>
          <th scope="col" style="width: 10%">Metacritic</th>
          <th scope="col" style="width: 20%">More Details</th>
        </tr>
        </thead>

        {% for game in game_list %}
        <tbody>
        <tr>
            <td class="align-middle d-none d-xl-table-cell"><img src="{{ game.image }}"></td>
            <td class="align-middle">{{ game.name }}</td>
            <td class="align-middle d-none d-md-table-cell">{{ game.developer }}</td>

            {% if game.metacritic == 0 %}
                <td class="align-middle">N/A</td>
            {% else %}
                <td class="align-middle">{{ game.metacritic }}</td>
            {% endif %}

            <!--The detail page requires a game ID as part of its URL, this grabs the game that is selected's ID-->
            <td class="align-middle"><a href="{% url 'games:detail' game.id %}"><img src="https://img.icons8.com/ios/50/000000/circled-right-2-filled.png"/></a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

<small><a href="https://icons8.com/icon/26196/forward-button-filled">Forward Button Filled icon by Icons8</a></small>
</div>

{% else %}
    <p>No games found! Please report this to Stuart.</p>
{% endif %}
</div>
</div>
{%  endblock %}

</body>
</html>

games/templates/games/recommended.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Recommended For You</title>
    {% extends 'games/base.html' %}

</head>
<body>

{% block body %}
<div class="content-section">
<div>

<h1>Recommended for you</h1>

{% if recommended_genres %}
    {% if recommended_genres.0.name == "2D" and recommended_genres.1.name == "Action" and recommended_genres.2.name == "Adventure" %}
    <p>Not enough preference data! Please help us identify the genres you enjoy by following <a href="{% url 'home:favourites' %}">this link</a></p>

{% else %}

<h4>These recommendations are based off your preference of the genres:<br>
    {{ recommended_genres.0 }}, {{ recommended_genres.1 }} and {{ recommended_genres.2 }}</h4><br>

{% if serendipitous_genre %}
    <h5>You don't seem to have shown much love towards {{ serendipitous_genre.first }} games, why not take a look at them
        <a href="{% url 'genre-results' %}?genre={{ serendipitous_genre.first }}&userid=None">here</a>?</h5>
{% endif %}

{% if game_list %}

<div class="table-responsive">
    <table class="table table-bordered">
        <!--Sets up headings-->
        <thead class="thead-dark">
        <tr>
          <!--d-none means don't show at all, d-#-table-cell overrides this
              and means show this column on screen sizes of # and larger-->
          <th scope="col" class="align-middle d-none d-xl-table-cell" style="width: 33.33%">Image</th>
          <th scope="col" class="align-middle" style="width: 16.66%">Title</th>
          <th scope="col" class="align-middle d-none d-md-table-cell" style="width: 7.5%">Developer</th>
          <th scope="col" class="align-middle d-none d-sm-table-cell" style="width: 7.5%">Metacritic</th>
          <th scope="col" class="align-middle" style="width: 17.5%">Because You Like</th>
          <th scope="col" class="align-middle" style="width: 17.5%">More Details</th>
        </tr>
        </thead>

        <!--Loop through each recommended game-->
        {% for game in game_list %}
        <tbody>
        <tr>
            <!--Add the game's details, d-#-table-cell determines when the column displays
                determined by the size of the screen on a small/medium/large/extra large scale-->
            <td class="align-middle d-none d-xl-table-cell"><img src="{{ game.image }}"></td>
            <td class="align-middle">{{ game.name }}</td>
            <td class="align-middle d-none d-md-table-cell">{{ game.developer }}</td>

            <!--As some games don't have a metacritic rating, in the database they are 0, so change 0 to N/A-->
            {% if game.metacritic == 0 %}
                <td class="align-middle">N/A</td>
            {% else %}
                <td class="align-middle d-none d-sm-table-cell">{{ game.metacritic }}</td>
            {% endif %}


            <!--Goes through each game's genres, when the current game has a genre which matches
                one or more of the user's preferred genres, then put this into the 'because
                you like' column to show which genres it is most applicable towards.-->
            {% if game.genres %}
                <td class="align-middle">
                    {% for genre in game.genres.all %}
                        {% for likedGenre in recommended_genres %}
                            {% if likedGenre == genre %}
                                {{ likedGenre }} <br><br>
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
                </td>
            {% else %}
                <td class="align-middle">N/A</td>
            {% endif %}


                <!--The detail page requires a game ID as part of its URL, this grabs the game that is selected's ID-->
                <td class="align-middle"><a href="{% url 'games:detail' game.id %}"><img src="https://img.icons8.com/ios/50/000000/circled-right-2-filled.png"/></a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <small><a href="https://icons8.com/icon/26196/forward-button-filled">Forward Button Filled icon by Icons8</a></small>
</div>

{% else %}
    <p>No games found! Please report this to Stuart.</p>
{% endif %}
{% endif %}
{% endif %}
</div>
</div>
{%  endblock %}



</body>
</html>